# Generated by Django 4.1.2 on 2022-12-02 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_employeeresume'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeresume',
            name='address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employeeresume',
            name='btechcgpa',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employeeresume',
            name='experience',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employeeresume',
            name='graduation',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employeeresume',
            name='intercollegegpa',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employeeresume',
            name='intercollegename',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employeeresume',
            name='qualifications',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employeeresume',
            name='sscgpa',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employeeresume',
            name='sscschool',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employeeresume',
            name='age',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
